== Test the deployment

. Configure the `kubectll` command line utility to connect to your EKS cluster. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/managing-auth.html[Cluster authentication^].
. Run `kubectl` to get namespaces, and verify that *snyk-monitor* namespace has a status of *Active*.
. Run `kubectl get pods --namespace snyk-monitor`, and verify that a pod with the *snyk-monitor* prefix has a status of *Running*.
. From the Snyk console, verify that your cluster appears and that you can add workloads. For more information, see https://support.snyk.io/hc/en-us/articles/360003947117#UUID-a0526554-0943-3363-6977-7a11f766ede2[Adding Kubernetes workloads for security scanning^].

== Best practices for using {partner-product-short-name} on EKS
The Snyk Kubernetes integration monitors workloads and provides details about potential vulnerabilities in container images as well as security configuration for your deployments. We recommended that your Kubernetes manifests adhere to the workload configuration properties. For more information, see https://support.snyk.io/hc/en-us/articles/360003916178-Viewing-project-details-and-test-results[Viewing project details and test results^].

== Security
Snyk alerts for common misconfigurations include not setting CPU or memory limits for your application as well as running containers as the root user. Another common misconfiguration is leaving the mounted default file system for the container as writable. This may expose you to attackers who compromise the container by writing to the disk. If your containers are stateless, you don’t need a writable file system.

Also, ensure to define capabilities. At a low level, Linux capabilities control what processes in the container can do, from writing to the disk to communicating over the network.
